image: gradle:7.4.2-jdk:jdk8

stages:
  - build
  - test
  - prod

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
<<<<<<< HEAD
    - gradle build
=======
    - gradle assemble
    
>>>>>>> 071d68711dad4cc7fbbab46892eb945e27da1399
