image: gradle:7.4.2-jdk:jdk8

stages:
  - build
  - test
  - prod

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

server_build:
  stage: build
  image: gradle:7.4.2-jdk:jdk8
  script:
    - cd src/server
    - ./gradlew build
